config/routes.rb
Foodtruck::Application.routes.draw do
  resources :trucks
 
  resources :users

  root 'users#new'
end

app/models/truck.rb
class Truck
  
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name,         type: String
  field :twitter_name, type: String
  field :twitter_id,   type: String
  
  has_many :tweets
  has_one :location
  belongs_to :user
  
  accepts_nested_attributes_for :location, reject_if: :all_blank, allow_destroy: true
  
  validates_presence_of   :name, :twitter_name, :twitter_id
  validates_uniqueness_of :name, :twitter_name, :twitter_id
  
  def self.permitted_params
  	[
  		:name,
  		:twitter_name,
  		:twitter_id
  	]
  end
end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
  before_action :set_truck, only: [:show, :edit, :update, :destroy]

  # GET /trucks
  # GET /trucks.json
  def index
    @trucks = Truck.all
  end

  # GET /trucks/1
  # GET /trucks/1.json
  def show
  end

  # GET /trucks/new
  def new
    @truck = Truck.new
    @location = @truck.build_location
    if params[:name].present?
      updater = TwitterApi.new
      @twitter_user = updater.find_user(params[:name])
    end
  end

  # GET /trucks/1/edit
  def edit
  end

  # POST /trucks
  # POST /trucks.json
  def create
    @truck = Truck.new(truck_params)

    respond_to do |format|
      if @truck.save
        format.html { redirect_to @truck, notice: 'Truck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @truck }
      else
        format.html { render action: 'new' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trucks/1
  # PATCH/PUT /trucks/1.json
  def update
    respond_to do |format|
      if @truck.update(truck_params)
        format.html { redirect_to @truck, notice: 'Truck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @truck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trucks/1
  # DELETE /trucks/1.json
  def destroy
    @truck.destroy
    respond_to do |format|
      format.html { redirect_to trucks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_truck
      @truck = Truck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def truck_params
      params.require(:truck).permit(*Truck.permitted_params, location_attributes: [:city, :state])
    end
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/views/trucks/_form.html.haml
%h3 Search for a Food Truck by Twitter name
= form_tag(params, :method => :get) do 
	= text_field_tag :name
	= submit_tag "Search", class: 'btn btn-primary'
	
- if params[:name].present?
	= @twitter_user.username
	= @twitter_user.name

	= form_for(@truck) do |f|
		= f.hidden_field :twitter_name, value: @twitter_user.user_name
		= f.hidden_field :name, value: @twitter_user.name
		= f.hidden_field :id, value: @twitter_user.id
		= f.fields_for(:location) do |builder|
			= builder.label :city, "City"
			= builder.text_field :city
			= builder.label :state, "State"
			= builder.select :state, UsStates.new.states
		= f.submit 'Create', class: 'btn btn-primary'

app/views/trucks/edit.html.haml
%h1 Editing truck

= render 'form'

= link_to 'Show', @truck
\|
= link_to 'Back', trucks_path

app/views/trucks/index.html.haml
%h1 Listing trucks

%table
  %tr
    %th
    %th
    %th

  - @trucks.each do |truck|
    %tr
      %td= link_to 'Show', truck
      %td= link_to 'Edit', edit_truck_path(truck)
      %td= link_to 'Destroy', truck, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Truck', new_truck_path

app/views/trucks/new.html.haml
%h1 New truck

= render 'form'

= link_to 'Back', trucks_path

app/views/trucks/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_truck_path(@truck)
\|
= link_to 'Back', trucks_path